### ISSUE TITLE
translateY in base stylesheet breaks fixed positioning

### ISSUE THREAD

**Issue by gpoitch** [ember-animation/liquid-fire#197]
Broken: http://jsbin.com/nuzelu/1/edit?html,css,output
Expected: http://jsbin.com/nuzelu/2/edit?html,css,output

This appears to be a known "bug" in Chrome:
https://code.google.com/p/chromium/issues/detail?id=20574

**Comment by Chun-Yang** [comment]
Is there any work around for this?

**Comment by ef4** [comment]
> Is there any work around for this?

You can use your CSS to override the default style provided by liquid-fire. Most things will still work without it -- but for certain animations you will get visible overflow that you don't want, and possible jumping of text as the antialiasing implementation changes at the start and end of animation.

**Comment by Chun-Yang** [comment]
If any one have this problem, I have a temporary solution: (This is for v0.17.0, you need to adjust to your own version)

-  disable default css transform
```css
.liquid-container {
  height: 100%;

  position: relative;
  overflow: initial;

  -webkit-transform: initial;
  -moz-transform:    initial;
  transform:         initial;
}
```

- clear transform after any transition. E.G. ```app/transitions/custom-to-up```
```javascript
export default function (oldView, insertNewView) {
  return this.lookup('move-over').call(this, oldView, insertNewView, 'y', -1)
    .then(function() {
      $('.liquid-child').css('transform', 'initial');
    });
}
```

BTW, thanks for your work! @ef4 :+1:

**Comment by jayswain** [comment]
If a css class got added to the liquid-container before the transition started, and was removed when the transition ended (maybe "transitioning", or "active"), and the CSS was scoped to that class, we could only break the layout during these times, which might be sufficient?

**Comment by ef4** [comment]
> If a css class got added to the liquid-container before the transition started

The problem with that is that it can cause your content to visibly jump at the moment the class is added, due to changes in antialiasing from non-accelerated to accelerated contexts.

But you can definitely override this in your own app when you don't care about that, and there is now a class on the liquid-container that gets automatically added for you only during transitions (https://github.com/ef4/liquid-fire/pull/209).

**Comment by bravo585** [comment]
Here's my solution, which is a slight modification of @Chun-Yang 's solution to work with version 0.19.3:

```css
.liquid-container > .liquid-child,
.liquid-container {
  transform: initial;
  overflow: initial;
}
```

```javascript
// app/transitions/custom-to-up
export default function (opts) {
  return this.lookup('move-over').call(this, 'y', -1, opts).then(() => {
    this.newElement.css('transform', '');
  });
}
```
